@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@server = http://{{host}}
@contentType = Content-Type: application/json

GET {{server}}/user

###

GET {{server}}/user/userpk1

###

POST {{server}}/user
{{contentType}}

{
  "name": "username 3",
  "email": "user_3@email.tld"
}

###

PUT {{server}}/user
{{contentType}}

{
  "name": "updated username 3",
  "email": "updated_user_3@email.tld",
  "pk": "userpk3"
}

###

DELETE {{server}}/user/userpk3
