@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@server = http://{{host}}
@contentType = Content-Type: application/json

GET {{server}}/user

###

POST {{server}}/user
{{contentType}}

{
    "name": "test user",
    "email": "test@email"
}
